// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/bus/v1/bus.proto

package buspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BusId         string                 `protobuf:"bytes,1,opt,name=bus_id,json=busId,proto3" json:"bus_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBusRequest) Reset() {
	*x = GetBusRequest{}
	mi := &file_proto_bus_v1_bus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBusRequest) ProtoMessage() {}

func (x *GetBusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bus_v1_bus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBusRequest.ProtoReflect.Descriptor instead.
func (*GetBusRequest) Descriptor() ([]byte, []int) {
	return file_proto_bus_v1_bus_proto_rawDescGZIP(), []int{0}
}

func (x *GetBusRequest) GetBusId() string {
	if x != nil {
		return x.BusId
	}
	return ""
}

type GetBusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bus           *Bus                   `protobuf:"bytes,1,opt,name=bus,proto3" json:"bus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBusResponse) Reset() {
	*x = GetBusResponse{}
	mi := &file_proto_bus_v1_bus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBusResponse) ProtoMessage() {}

func (x *GetBusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bus_v1_bus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBusResponse.ProtoReflect.Descriptor instead.
func (*GetBusResponse) Descriptor() ([]byte, []int) {
	return file_proto_bus_v1_bus_proto_rawDescGZIP(), []int{1}
}

func (x *GetBusResponse) GetBus() *Bus {
	if x != nil {
		return x.Bus
	}
	return nil
}

type Bus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LicensePlate   string                 `protobuf:"bytes,2,opt,name=license_plate,json=licensePlate,proto3" json:"license_plate,omitempty"`
	FromLocation   string                 `protobuf:"bytes,3,opt,name=from_location,json=fromLocation,proto3" json:"from_location,omitempty"`
	ToLocation     string                 `protobuf:"bytes,4,opt,name=to_location,json=toLocation,proto3" json:"to_location,omitempty"`
	DepartureTime  string                 `protobuf:"bytes,5,opt,name=departure_time,json=departureTime,proto3" json:"departure_time,omitempty"`
	TotalSeats     int32                  `protobuf:"varint,6,opt,name=total_seats,json=totalSeats,proto3" json:"total_seats,omitempty"`
	AvailableSeats int32                  `protobuf:"varint,7,opt,name=available_seats,json=availableSeats,proto3" json:"available_seats,omitempty"`
	Price          float64                `protobuf:"fixed64,8,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Bus) Reset() {
	*x = Bus{}
	mi := &file_proto_bus_v1_bus_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bus) ProtoMessage() {}

func (x *Bus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bus_v1_bus_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bus.ProtoReflect.Descriptor instead.
func (*Bus) Descriptor() ([]byte, []int) {
	return file_proto_bus_v1_bus_proto_rawDescGZIP(), []int{2}
}

func (x *Bus) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Bus) GetLicensePlate() string {
	if x != nil {
		return x.LicensePlate
	}
	return ""
}

func (x *Bus) GetFromLocation() string {
	if x != nil {
		return x.FromLocation
	}
	return ""
}

func (x *Bus) GetToLocation() string {
	if x != nil {
		return x.ToLocation
	}
	return ""
}

func (x *Bus) GetDepartureTime() string {
	if x != nil {
		return x.DepartureTime
	}
	return ""
}

func (x *Bus) GetTotalSeats() int32 {
	if x != nil {
		return x.TotalSeats
	}
	return 0
}

func (x *Bus) GetAvailableSeats() int32 {
	if x != nil {
		return x.AvailableSeats
	}
	return 0
}

func (x *Bus) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type GetSeatsByCodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BusId         string                 `protobuf:"bytes,1,opt,name=bus_id,json=busId,proto3" json:"bus_id,omitempty"`
	SeatCodes     []string               `protobuf:"bytes,2,rep,name=seat_codes,json=seatCodes,proto3" json:"seat_codes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSeatsByCodesRequest) Reset() {
	*x = GetSeatsByCodesRequest{}
	mi := &file_proto_bus_v1_bus_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeatsByCodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeatsByCodesRequest) ProtoMessage() {}

func (x *GetSeatsByCodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bus_v1_bus_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeatsByCodesRequest.ProtoReflect.Descriptor instead.
func (*GetSeatsByCodesRequest) Descriptor() ([]byte, []int) {
	return file_proto_bus_v1_bus_proto_rawDescGZIP(), []int{3}
}

func (x *GetSeatsByCodesRequest) GetBusId() string {
	if x != nil {
		return x.BusId
	}
	return ""
}

func (x *GetSeatsByCodesRequest) GetSeatCodes() []string {
	if x != nil {
		return x.SeatCodes
	}
	return nil
}

type GetSeatsByCodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seats         []*Seat                `protobuf:"bytes,1,rep,name=seats,proto3" json:"seats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSeatsByCodesResponse) Reset() {
	*x = GetSeatsByCodesResponse{}
	mi := &file_proto_bus_v1_bus_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeatsByCodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeatsByCodesResponse) ProtoMessage() {}

func (x *GetSeatsByCodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bus_v1_bus_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeatsByCodesResponse.ProtoReflect.Descriptor instead.
func (*GetSeatsByCodesResponse) Descriptor() ([]byte, []int) {
	return file_proto_bus_v1_bus_proto_rawDescGZIP(), []int{4}
}

func (x *GetSeatsByCodesResponse) GetSeats() []*Seat {
	if x != nil {
		return x.Seats
	}
	return nil
}

type Seat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BusId         string                 `protobuf:"bytes,2,opt,name=bus_id,json=busId,proto3" json:"bus_id,omitempty"`
	SeatCode      string                 `protobuf:"bytes,3,opt,name=seat_code,json=seatCode,proto3" json:"seat_code,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Seat) Reset() {
	*x = Seat{}
	mi := &file_proto_bus_v1_bus_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Seat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Seat) ProtoMessage() {}

func (x *Seat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bus_v1_bus_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Seat.ProtoReflect.Descriptor instead.
func (*Seat) Descriptor() ([]byte, []int) {
	return file_proto_bus_v1_bus_proto_rawDescGZIP(), []int{5}
}

func (x *Seat) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Seat) GetBusId() string {
	if x != nil {
		return x.BusId
	}
	return ""
}

func (x *Seat) GetSeatCode() string {
	if x != nil {
		return x.SeatCode
	}
	return ""
}

func (x *Seat) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type BookSeatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BusId         string                 `protobuf:"bytes,1,opt,name=bus_id,json=busId,proto3" json:"bus_id,omitempty"`
	SeatCodes     []string               `protobuf:"bytes,2,rep,name=seat_codes,json=seatCodes,proto3" json:"seat_codes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookSeatsRequest) Reset() {
	*x = BookSeatsRequest{}
	mi := &file_proto_bus_v1_bus_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookSeatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookSeatsRequest) ProtoMessage() {}

func (x *BookSeatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bus_v1_bus_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookSeatsRequest.ProtoReflect.Descriptor instead.
func (*BookSeatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_bus_v1_bus_proto_rawDescGZIP(), []int{6}
}

func (x *BookSeatsRequest) GetBusId() string {
	if x != nil {
		return x.BusId
	}
	return ""
}

func (x *BookSeatsRequest) GetSeatCodes() []string {
	if x != nil {
		return x.SeatCodes
	}
	return nil
}

type BookSeatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookSeatsResponse) Reset() {
	*x = BookSeatsResponse{}
	mi := &file_proto_bus_v1_bus_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookSeatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookSeatsResponse) ProtoMessage() {}

func (x *BookSeatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bus_v1_bus_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookSeatsResponse.ProtoReflect.Descriptor instead.
func (*BookSeatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_bus_v1_bus_proto_rawDescGZIP(), []int{7}
}

func (x *BookSeatsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_bus_v1_bus_proto protoreflect.FileDescriptor

const file_proto_bus_v1_bus_proto_rawDesc = "" +
	"\n" +
	"\x16proto/bus/v1/bus.proto\x12\x06bus.v1\"&\n" +
	"\rGetBusRequest\x12\x15\n" +
	"\x06bus_id\x18\x01 \x01(\tR\x05busId\"/\n" +
	"\x0eGetBusResponse\x12\x1d\n" +
	"\x03bus\x18\x01 \x01(\v2\v.bus.v1.BusR\x03bus\"\x87\x02\n" +
	"\x03Bus\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rlicense_plate\x18\x02 \x01(\tR\flicensePlate\x12#\n" +
	"\rfrom_location\x18\x03 \x01(\tR\ffromLocation\x12\x1f\n" +
	"\vto_location\x18\x04 \x01(\tR\n" +
	"toLocation\x12%\n" +
	"\x0edeparture_time\x18\x05 \x01(\tR\rdepartureTime\x12\x1f\n" +
	"\vtotal_seats\x18\x06 \x01(\x05R\n" +
	"totalSeats\x12'\n" +
	"\x0favailable_seats\x18\a \x01(\x05R\x0eavailableSeats\x12\x14\n" +
	"\x05price\x18\b \x01(\x01R\x05price\"N\n" +
	"\x16GetSeatsByCodesRequest\x12\x15\n" +
	"\x06bus_id\x18\x01 \x01(\tR\x05busId\x12\x1d\n" +
	"\n" +
	"seat_codes\x18\x02 \x03(\tR\tseatCodes\"=\n" +
	"\x17GetSeatsByCodesResponse\x12\"\n" +
	"\x05seats\x18\x01 \x03(\v2\f.bus.v1.SeatR\x05seats\"b\n" +
	"\x04Seat\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06bus_id\x18\x02 \x01(\tR\x05busId\x12\x1b\n" +
	"\tseat_code\x18\x03 \x01(\tR\bseatCode\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"H\n" +
	"\x10BookSeatsRequest\x12\x15\n" +
	"\x06bus_id\x18\x01 \x01(\tR\x05busId\x12\x1d\n" +
	"\n" +
	"seat_codes\x18\x02 \x03(\tR\tseatCodes\"-\n" +
	"\x11BookSeatsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xdb\x01\n" +
	"\n" +
	"BusService\x127\n" +
	"\x06GetBus\x12\x15.bus.v1.GetBusRequest\x1a\x16.bus.v1.GetBusResponse\x12R\n" +
	"\x0fGetSeatsByCodes\x12\x1e.bus.v1.GetSeatsByCodesRequest\x1a\x1f.bus.v1.GetSeatsByCodesResponse\x12@\n" +
	"\tBookSeats\x12\x18.bus.v1.BookSeatsRequest\x1a\x19.bus.v1.BookSeatsResponseB#Z!booking-system/proto/bus/v1;buspbb\x06proto3"

var (
	file_proto_bus_v1_bus_proto_rawDescOnce sync.Once
	file_proto_bus_v1_bus_proto_rawDescData []byte
)

func file_proto_bus_v1_bus_proto_rawDescGZIP() []byte {
	file_proto_bus_v1_bus_proto_rawDescOnce.Do(func() {
		file_proto_bus_v1_bus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_bus_v1_bus_proto_rawDesc), len(file_proto_bus_v1_bus_proto_rawDesc)))
	})
	return file_proto_bus_v1_bus_proto_rawDescData
}

var file_proto_bus_v1_bus_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_bus_v1_bus_proto_goTypes = []any{
	(*GetBusRequest)(nil),           // 0: bus.v1.GetBusRequest
	(*GetBusResponse)(nil),          // 1: bus.v1.GetBusResponse
	(*Bus)(nil),                     // 2: bus.v1.Bus
	(*GetSeatsByCodesRequest)(nil),  // 3: bus.v1.GetSeatsByCodesRequest
	(*GetSeatsByCodesResponse)(nil), // 4: bus.v1.GetSeatsByCodesResponse
	(*Seat)(nil),                    // 5: bus.v1.Seat
	(*BookSeatsRequest)(nil),        // 6: bus.v1.BookSeatsRequest
	(*BookSeatsResponse)(nil),       // 7: bus.v1.BookSeatsResponse
}
var file_proto_bus_v1_bus_proto_depIdxs = []int32{
	2, // 0: bus.v1.GetBusResponse.bus:type_name -> bus.v1.Bus
	5, // 1: bus.v1.GetSeatsByCodesResponse.seats:type_name -> bus.v1.Seat
	0, // 2: bus.v1.BusService.GetBus:input_type -> bus.v1.GetBusRequest
	3, // 3: bus.v1.BusService.GetSeatsByCodes:input_type -> bus.v1.GetSeatsByCodesRequest
	6, // 4: bus.v1.BusService.BookSeats:input_type -> bus.v1.BookSeatsRequest
	1, // 5: bus.v1.BusService.GetBus:output_type -> bus.v1.GetBusResponse
	4, // 6: bus.v1.BusService.GetSeatsByCodes:output_type -> bus.v1.GetSeatsByCodesResponse
	7, // 7: bus.v1.BusService.BookSeats:output_type -> bus.v1.BookSeatsResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_bus_v1_bus_proto_init() }
func file_proto_bus_v1_bus_proto_init() {
	if File_proto_bus_v1_bus_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_bus_v1_bus_proto_rawDesc), len(file_proto_bus_v1_bus_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_bus_v1_bus_proto_goTypes,
		DependencyIndexes: file_proto_bus_v1_bus_proto_depIdxs,
		MessageInfos:      file_proto_bus_v1_bus_proto_msgTypes,
	}.Build()
	File_proto_bus_v1_bus_proto = out.File
	file_proto_bus_v1_bus_proto_goTypes = nil
	file_proto_bus_v1_bus_proto_depIdxs = nil
}
