syntax = "proto3";

package bus.v1;

option go_package = "booking-system/proto/bus/v1;buspb";

service BusService {
  rpc GetBus(GetBusRequest) 
    returns (GetBusResponse);
  rpc GetSeatsByCodes(GetSeatsByCodesRequest) 
    returns (GetSeatsByCodesResponse);
  rpc BookSeats(BookSeatsRequest) 
    returns (BookSeatsResponse);
  rpc CreateBus(CreateBusRequest) 
    returns (CreateBusResponse);
  rpc ListBuses(ListBusesRequest) 
    returns (ListBusesResponse);
  rpc GetSeats(GetSeatsRequest) 
    returns (GetSeatsResponse);
  rpc DeleteBus(DeleteBusRequest) 
    returns (DeleteBusResponse);
  rpc MarkBookedByBookingID(MarkBookedByBookingIDRequest)
    returns (MarkBookedByBookingIDResponse);
  rpc GetSeatByBookingID(GetSeatByBookingIDRequest)
    returns (GetSeatByBookingIDResponse);
  rpc ReleaseSeatsByBookingID(ReleaseSeatsByBookingIDRequest)
    returns (ReleaseSeatsByBookingIDResponse);
}

message GetBusRequest {
  string bus_id = 1;
}

message GetBusResponse {
  Bus bus = 1;
}

message Bus {
  string id = 1;
  string license_plate = 2;
  string from_location = 3;
  string to_location = 4;
  string departure_time = 5;
  int32 total_seats = 6;
  int32 available_seats = 7;
  double price = 8;
} 

message GetSeatsByCodesRequest {
  string bus_id = 1;
  repeated string seat_codes = 2;
}

message GetSeatsByCodesResponse {
  repeated Seat seats = 1;
}

message Seat {
  string id = 1;
  string bus_id = 2;
  string seat_code = 3;
  string status = 4;
}

message BookSeatsRequest {
  string bus_id = 1;
  repeated string seat_codes = 2;
}
message BookSeatsResponse {
  bool success = 1;
}

message CreateBusRequest {
  string license_plate = 1;
  string from_location = 2;
  string to_location = 3;
  string departure_time = 4;
  double price = 5;
  repeated string row_name = 6;
  int32 seats_per_row = 7;
}
message CreateBusResponse {
  Bus bus = 1;
}
message ListBusesRequest {}
message ListBusesResponse {
  repeated Bus buses = 1;
}
message GetSeatsRequest {
  string bus_id = 1;
}
message GetSeatsResponse {
  repeated Seat seats = 1;
}
message DeleteBusRequest {
  string bus_id = 1;
}
message DeleteBusResponse {
  bool success = 1;
}

message MarkBookedByBookingIDRequest {
  string booking_id = 1;
  string bus_id = 2;
  int32 count = 3;
}
message MarkBookedByBookingIDResponse {
  bool success = 1;
}

message GetSeatByBookingIDRequest {
  string booking_id = 1;
}
message GetSeatByBookingIDResponse {
  repeated Seat seats = 1;
}

message ReleaseSeatsByBookingIDRequest {
  string booking_id = 1;
}
message ReleaseSeatsByBookingIDResponse {
  bool success = 1;
}