// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: proto/bus/v1/bus.proto

package buspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BusService_GetBus_FullMethodName          = "/bus.v1.BusService/GetBus"
	BusService_GetSeatsByCodes_FullMethodName = "/bus.v1.BusService/GetSeatsByCodes"
	BusService_BookSeats_FullMethodName       = "/bus.v1.BusService/BookSeats"
	BusService_CreateBus_FullMethodName       = "/bus.v1.BusService/CreateBus"
	BusService_ListBuses_FullMethodName       = "/bus.v1.BusService/ListBuses"
	BusService_GetSeats_FullMethodName        = "/bus.v1.BusService/GetSeats"
	BusService_DeleteBus_FullMethodName       = "/bus.v1.BusService/DeleteBus"
)

// BusServiceClient is the client API for BusService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BusServiceClient interface {
	GetBus(ctx context.Context, in *GetBusRequest, opts ...grpc.CallOption) (*GetBusResponse, error)
	GetSeatsByCodes(ctx context.Context, in *GetSeatsByCodesRequest, opts ...grpc.CallOption) (*GetSeatsByCodesResponse, error)
	BookSeats(ctx context.Context, in *BookSeatsRequest, opts ...grpc.CallOption) (*BookSeatsResponse, error)
	CreateBus(ctx context.Context, in *CreateBusRequest, opts ...grpc.CallOption) (*CreateBusResponse, error)
	ListBuses(ctx context.Context, in *ListBusesRequest, opts ...grpc.CallOption) (*ListBusesResponse, error)
	GetSeats(ctx context.Context, in *GetSeatsRequest, opts ...grpc.CallOption) (*GetSeatsResponse, error)
	DeleteBus(ctx context.Context, in *DeleteBusRequest, opts ...grpc.CallOption) (*DeleteBusResponse, error)
}

type busServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBusServiceClient(cc grpc.ClientConnInterface) BusServiceClient {
	return &busServiceClient{cc}
}

func (c *busServiceClient) GetBus(ctx context.Context, in *GetBusRequest, opts ...grpc.CallOption) (*GetBusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBusResponse)
	err := c.cc.Invoke(ctx, BusService_GetBus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *busServiceClient) GetSeatsByCodes(ctx context.Context, in *GetSeatsByCodesRequest, opts ...grpc.CallOption) (*GetSeatsByCodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSeatsByCodesResponse)
	err := c.cc.Invoke(ctx, BusService_GetSeatsByCodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *busServiceClient) BookSeats(ctx context.Context, in *BookSeatsRequest, opts ...grpc.CallOption) (*BookSeatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BookSeatsResponse)
	err := c.cc.Invoke(ctx, BusService_BookSeats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *busServiceClient) CreateBus(ctx context.Context, in *CreateBusRequest, opts ...grpc.CallOption) (*CreateBusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateBusResponse)
	err := c.cc.Invoke(ctx, BusService_CreateBus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *busServiceClient) ListBuses(ctx context.Context, in *ListBusesRequest, opts ...grpc.CallOption) (*ListBusesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBusesResponse)
	err := c.cc.Invoke(ctx, BusService_ListBuses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *busServiceClient) GetSeats(ctx context.Context, in *GetSeatsRequest, opts ...grpc.CallOption) (*GetSeatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSeatsResponse)
	err := c.cc.Invoke(ctx, BusService_GetSeats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *busServiceClient) DeleteBus(ctx context.Context, in *DeleteBusRequest, opts ...grpc.CallOption) (*DeleteBusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteBusResponse)
	err := c.cc.Invoke(ctx, BusService_DeleteBus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BusServiceServer is the server API for BusService service.
// All implementations must embed UnimplementedBusServiceServer
// for forward compatibility.
type BusServiceServer interface {
	GetBus(context.Context, *GetBusRequest) (*GetBusResponse, error)
	GetSeatsByCodes(context.Context, *GetSeatsByCodesRequest) (*GetSeatsByCodesResponse, error)
	BookSeats(context.Context, *BookSeatsRequest) (*BookSeatsResponse, error)
	CreateBus(context.Context, *CreateBusRequest) (*CreateBusResponse, error)
	ListBuses(context.Context, *ListBusesRequest) (*ListBusesResponse, error)
	GetSeats(context.Context, *GetSeatsRequest) (*GetSeatsResponse, error)
	DeleteBus(context.Context, *DeleteBusRequest) (*DeleteBusResponse, error)
	mustEmbedUnimplementedBusServiceServer()
}

// UnimplementedBusServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBusServiceServer struct{}

func (UnimplementedBusServiceServer) GetBus(context.Context, *GetBusRequest) (*GetBusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBus not implemented")
}
func (UnimplementedBusServiceServer) GetSeatsByCodes(context.Context, *GetSeatsByCodesRequest) (*GetSeatsByCodesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSeatsByCodes not implemented")
}
func (UnimplementedBusServiceServer) BookSeats(context.Context, *BookSeatsRequest) (*BookSeatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BookSeats not implemented")
}
func (UnimplementedBusServiceServer) CreateBus(context.Context, *CreateBusRequest) (*CreateBusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBus not implemented")
}
func (UnimplementedBusServiceServer) ListBuses(context.Context, *ListBusesRequest) (*ListBusesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBuses not implemented")
}
func (UnimplementedBusServiceServer) GetSeats(context.Context, *GetSeatsRequest) (*GetSeatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSeats not implemented")
}
func (UnimplementedBusServiceServer) DeleteBus(context.Context, *DeleteBusRequest) (*DeleteBusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBus not implemented")
}
func (UnimplementedBusServiceServer) mustEmbedUnimplementedBusServiceServer() {}
func (UnimplementedBusServiceServer) testEmbeddedByValue()                    {}

// UnsafeBusServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BusServiceServer will
// result in compilation errors.
type UnsafeBusServiceServer interface {
	mustEmbedUnimplementedBusServiceServer()
}

func RegisterBusServiceServer(s grpc.ServiceRegistrar, srv BusServiceServer) {
	// If the following call panics, it indicates UnimplementedBusServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BusService_ServiceDesc, srv)
}

func _BusService_GetBus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusServiceServer).GetBus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BusService_GetBus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusServiceServer).GetBus(ctx, req.(*GetBusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BusService_GetSeatsByCodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSeatsByCodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusServiceServer).GetSeatsByCodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BusService_GetSeatsByCodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusServiceServer).GetSeatsByCodes(ctx, req.(*GetSeatsByCodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BusService_BookSeats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookSeatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusServiceServer).BookSeats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BusService_BookSeats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusServiceServer).BookSeats(ctx, req.(*BookSeatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BusService_CreateBus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusServiceServer).CreateBus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BusService_CreateBus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusServiceServer).CreateBus(ctx, req.(*CreateBusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BusService_ListBuses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBusesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusServiceServer).ListBuses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BusService_ListBuses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusServiceServer).ListBuses(ctx, req.(*ListBusesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BusService_GetSeats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSeatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusServiceServer).GetSeats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BusService_GetSeats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusServiceServer).GetSeats(ctx, req.(*GetSeatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BusService_DeleteBus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusServiceServer).DeleteBus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BusService_DeleteBus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusServiceServer).DeleteBus(ctx, req.(*DeleteBusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BusService_ServiceDesc is the grpc.ServiceDesc for BusService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BusService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bus.v1.BusService",
	HandlerType: (*BusServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBus",
			Handler:    _BusService_GetBus_Handler,
		},
		{
			MethodName: "GetSeatsByCodes",
			Handler:    _BusService_GetSeatsByCodes_Handler,
		},
		{
			MethodName: "BookSeats",
			Handler:    _BusService_BookSeats_Handler,
		},
		{
			MethodName: "CreateBus",
			Handler:    _BusService_CreateBus_Handler,
		},
		{
			MethodName: "ListBuses",
			Handler:    _BusService_ListBuses_Handler,
		},
		{
			MethodName: "GetSeats",
			Handler:    _BusService_GetSeats_Handler,
		},
		{
			MethodName: "DeleteBus",
			Handler:    _BusService_DeleteBus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/bus/v1/bus.proto",
}
