global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    dns_sd_configs:
      - names:
          - 'tasks.api'
        type: 'A'
        port: 8080

  - job_name: 'ws-service'
    dns_sd_configs:
      - names:
          - 'tasks.ws-service'
        type: 'A'
        port: 8082

  - job_name: 'bus-service'
    dns_sd_configs:
      - names:
          - 'tasks.bus-service'
        type: 'A'
        port: 9091

  - job_name: 'booking-service'
    dns_sd_configs:
      - names:
          - 'tasks.booking-service'
        type: 'A'
        port: 9092

  - job_name: 'user-service'
    dns_sd_configs:
      - names:
          - 'tasks.user-service'
        type: 'A'
        port: 9093

  - job_name: 'payment-service'
    dns_sd_configs:
      - names:
          - 'tasks.payment-service'
        type: 'A'
        port: 9094

  - job_name: 'notification-service'
    dns_sd_configs:
      - names:
          - 'tasks.notification-service'
        type: 'A'
        port: 9095
