// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/booking/v1/booking.proto

package bookingpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfirmBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BusId         string                 `protobuf:"bytes,1,opt,name=bus_id,json=busId,proto3" json:"bus_id,omitempty"`
	SeatCodes     []string               `protobuf:"bytes,2,rep,name=seat_codes,json=seatCodes,proto3" json:"seat_codes,omitempty"`
	UserName      string                 `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	TempUserId    string                 `protobuf:"bytes,6,opt,name=temp_user_id,json=tempUserId,proto3" json:"temp_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmBookingRequest) Reset() {
	*x = ConfirmBookingRequest{}
	mi := &file_proto_booking_v1_booking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmBookingRequest) ProtoMessage() {}

func (x *ConfirmBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_v1_booking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmBookingRequest.ProtoReflect.Descriptor instead.
func (*ConfirmBookingRequest) Descriptor() ([]byte, []int) {
	return file_proto_booking_v1_booking_proto_rawDescGZIP(), []int{0}
}

func (x *ConfirmBookingRequest) GetBusId() string {
	if x != nil {
		return x.BusId
	}
	return ""
}

func (x *ConfirmBookingRequest) GetSeatCodes() []string {
	if x != nil {
		return x.SeatCodes
	}
	return nil
}

func (x *ConfirmBookingRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *ConfirmBookingRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ConfirmBookingRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *ConfirmBookingRequest) GetTempUserId() string {
	if x != nil {
		return x.TempUserId
	}
	return ""
}

type ConfirmBookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	TotalAmount   float64                `protobuf:"fixed64,2,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmBookingResponse) Reset() {
	*x = ConfirmBookingResponse{}
	mi := &file_proto_booking_v1_booking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmBookingResponse) ProtoMessage() {}

func (x *ConfirmBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_v1_booking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmBookingResponse.ProtoReflect.Descriptor instead.
func (*ConfirmBookingResponse) Descriptor() ([]byte, []int) {
	return file_proto_booking_v1_booking_proto_rawDescGZIP(), []int{1}
}

func (x *ConfirmBookingResponse) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *ConfirmBookingResponse) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *ConfirmBookingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_booking_v1_booking_proto protoreflect.FileDescriptor

const file_proto_booking_v1_booking_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/booking/v1/booking.proto\x12\n" +
	"booking.v1\"\xb8\x01\n" +
	"\x15ConfirmBookingRequest\x12\x15\n" +
	"\x06bus_id\x18\x01 \x01(\tR\x05busId\x12\x1d\n" +
	"\n" +
	"seat_codes\x18\x02 \x03(\tR\tseatCodes\x12\x1b\n" +
	"\tuser_name\x18\x03 \x01(\tR\buserName\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12 \n" +
	"\ftemp_user_id\x18\x06 \x01(\tR\n" +
	"tempUserId\"r\n" +
	"\x16ConfirmBookingResponse\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\x12!\n" +
	"\ftotal_amount\x18\x02 \x01(\x01R\vtotalAmount\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status2i\n" +
	"\x0eBookingService\x12W\n" +
	"\x0eConfirmBooking\x12!.booking.v1.ConfirmBookingRequest\x1a\".booking.v1.ConfirmBookingResponseB+Z)booking-system/proto/booking/v1;bookingpbb\x06proto3"

var (
	file_proto_booking_v1_booking_proto_rawDescOnce sync.Once
	file_proto_booking_v1_booking_proto_rawDescData []byte
)

func file_proto_booking_v1_booking_proto_rawDescGZIP() []byte {
	file_proto_booking_v1_booking_proto_rawDescOnce.Do(func() {
		file_proto_booking_v1_booking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_booking_v1_booking_proto_rawDesc), len(file_proto_booking_v1_booking_proto_rawDesc)))
	})
	return file_proto_booking_v1_booking_proto_rawDescData
}

var file_proto_booking_v1_booking_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_booking_v1_booking_proto_goTypes = []any{
	(*ConfirmBookingRequest)(nil),  // 0: booking.v1.ConfirmBookingRequest
	(*ConfirmBookingResponse)(nil), // 1: booking.v1.ConfirmBookingResponse
}
var file_proto_booking_v1_booking_proto_depIdxs = []int32{
	0, // 0: booking.v1.BookingService.ConfirmBooking:input_type -> booking.v1.ConfirmBookingRequest
	1, // 1: booking.v1.BookingService.ConfirmBooking:output_type -> booking.v1.ConfirmBookingResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_booking_v1_booking_proto_init() }
func file_proto_booking_v1_booking_proto_init() {
	if File_proto_booking_v1_booking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_booking_v1_booking_proto_rawDesc), len(file_proto_booking_v1_booking_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_booking_v1_booking_proto_goTypes,
		DependencyIndexes: file_proto_booking_v1_booking_proto_depIdxs,
		MessageInfos:      file_proto_booking_v1_booking_proto_msgTypes,
	}.Build()
	File_proto_booking_v1_booking_proto = out.File
	file_proto_booking_v1_booking_proto_goTypes = nil
	file_proto_booking_v1_booking_proto_depIdxs = nil
}
